//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoArrow.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.arcayn.com/asherons-call/maps/")]
        public string DungeonBaseURL {
            get {
                return ((string)(this["DungeonBaseURL"]));
            }
            set {
                this["DungeonBaseURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.arcayn.com/asherons-call/maps/dungeon_ids.csv.notimportantanymore")]
        public string DungeonListURL {
            get {
                return ((string)(this["DungeonListURL"]));
            }
            set {
                this["DungeonListURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int MapCacheRefreshDays {
            get {
                return ((int)(this["MapCacheRefreshDays"]));
            }
            set {
                this["MapCacheRefreshDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int DungeonListCacheRefreshDays {
            get {
                return ((int)(this["DungeonListCacheRefreshDays"]));
            }
            set {
                this["DungeonListCacheRefreshDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int BlacklistAgeDays {
            get {
                return ((int)(this["BlacklistAgeDays"]));
            }
            set {
                this["BlacklistAgeDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.arcayn.com/asherons-call/maps/dungeons.txt")]
        public string DungeonCacheFile {
            get {
                return ((string)(this["DungeonCacheFile"]));
            }
            set {
                this["DungeonCacheFile"] = value;
            }
        }
    }
}
